sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build paper/whitepaper.tex
- bibtex _build/whitepaper
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build paper/whitepaper.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build paper/whitepaper.tex
deploy:
  provider: releases
  api_key:
    secure: Ohn5HNWBL/Z3JFZQtcBAgGfvjVkgSHAE/jO0tMsOe6EgvlsvmAl6qEdKHpkEpECepbr/VI8i98Hak37K2EKOOqoCwqIU8MYiWIpVtv3jpDTIrZ/xS5sN5X59w0hsmEnzXvLN6jUgIb1i1Cgs0mXRXyHl3+Y7IKPrpzn0upaPRsMkZpO/xGYI85+J1Qd9hJloN+4CsZI5FhwZnZLWiNfc94afRiDUV4Yh+0EUbfmz/2kY5qymRMj/Rq3dz6UYq8RmhbaMJ/odGol9OeSjpf34lAQBPQ49jKUSuYYdd7lKmBe1OeZpAdhzf0Op0m8OHvNgUosJmhS2XmUDQlsyFRZFfowI9VdFvSI3f1rd3SYJBKJyyJ/tpO63Hn8Sn5LQ2cI7ZZAlP6zRZ9AS5tzS8jwopUJ/HWl1z/1Lszo8uArzMrhxQox5VfDfbXv8ySLXobLXn9s/Fqrr9+ivElhRLnqMnPVguf8A1QolgX2ihGr6/NTLbKIBynuuyOlD1THeyXo371IBcAbY5P+2SPzfPJ/Hs+clePCewt+2FbBc+TJseJXuCl6RDYVSedwYQsxZh04/aAQKSuG8mvXoXEOBEK+YZlXe/goWmC0BuWk7/GuOq3u3Od6U0SC2IctdppYz068yK06osw1WMCvQj18Y91DMvtyAkSyEG+rGEA6MkBuMkCQ=
  file:
  - _build/whitepaper.pdf
  skip_cleanup: true
  on:
    tags: true
