name: paper-maker
# description: Automagically build LaTex manuscripts and push the latest PDF back to GitHub

on: 
  push:
    tags:
    - '*'

# branding:
#   icon: 'zap'
#   color: 'blue'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    env:
      BUILD_PATH: _build
      SOURCE_PATH: paper
      FILE: whitepaper
      MANUSCRIPT_PATH: paper/whitepaper # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex -shell-escape
      BIBTEX: bibtex
    steps: 
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra
    - name: Build paper
      run: |
        mkdir ${BUILD_PATH}
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH}.tex
        ${BIBTEX} ${BUILD_PATH}/${FILE}
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH}.tex
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH}.tex
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "${BUILD_PATH}/${FILE}.pdf"
        # bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}