name: paper-maker
# description: Automagically build LaTex manuscripts and push the latest PDF back to GitHub

on: push

# branding:
#   icon: 'zap'
#   color: 'blue'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: _build
      MANUSCRIPT_PATH: paper/whitepaper # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex -shell-escape
      BIBTEX: bibtex
    steps: 
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra
    - name: Build paper
      run: |
        mkdir ${BUILD_PATH}
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH##*/}.tex
        ${BIBTEX} ${BUILD_PATH##*/}.aux
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH##*/}.tex
        ${LATEX} -interaction=nonstopmode -halt-on-error -output-directory ${BUILD_PATH} ${MANUSCRIPT_PATH##*/}.tex
    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        git rm -rf .github/
        cd ${MANUSCRIPT_PATH%/*}
        git rm -rf . 
        git add -f ${MANUSCRIPT_PATH##*/}.pdf
        git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf